# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06\x64\x65vice\"3\n\x0e\x43ommandRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\">\n\rConfigRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8c\x01\n\rDeviceService\x12=\n\tSetStatus\x12\x16.device.CommandRequest\x1a\x16.device.StatusResponse\"\x00\x12<\n\tSetConfig\x12\x15.device.ConfigRequest\x1a\x16.device.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=24
  _globals['_COMMANDREQUEST']._serialized_end=75
  _globals['_CONFIGREQUEST']._serialized_start=77
  _globals['_CONFIGREQUEST']._serialized_end=139
  _globals['_STATUSRESPONSE']._serialized_start=141
  _globals['_STATUSRESPONSE']._serialized_end=174
  _globals['_DEVICESERVICE']._serialized_start=177
  _globals['_DEVICESERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
